# Install Docker and Docker Compose
- name: Install Docker
  hosts: wordpress
  become: yes
  tasks:
    - name: Update package list
      apt:
        update_cache: yes

    - name: Install Docker dependencies
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - make

    - name: Add Docker's official GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: present

    - name: Create docker group
      group:
        name: docker
        state: present

    - name: Add user to docker group
      user:
        name: ubuntu
        groups: docker
        append: yes

# Enable and start Docker service
- name: Manage Docker Service
  hosts: wordpress
  become: yes
  tasks:
    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: yes

# Copy the docker webapp
- name: Copy the docker webapp
  hosts: wordpress
  become: yes
  tasks:
    - name:
      copy:
        src: ../docker-webapp/
        dest: /home/ubuntu/webapp/
